//
// Created by Nico Russo on 4/18/26.
//

#ifndef MEDIUM_MOUSEBUTTONS_H
#define MEDIUM_MOUSEBUTTONS_H

#define MED_MOUSE_BUTTON_1         0
#define MED_MOUSE_BUTTON_2         1
#define MED_MOUSE_BUTTON_3         2
#define MED_MOUSE_BUTTON_4         3
#define MED_MOUSE_BUTTON_5         4
#define MED_MOUSE_BUTTON_6         5
#define MED_MOUSE_BUTTON_7         6
#define MED_MOUSE_BUTTON_8         7
#define MED_MOUSE_BUTTON_LAST      MED_MOUSE_BUTTON_8
#define MED_MOUSE_BUTTON_LEFT      MED_MOUSE_BUTTON_1
#define MED_MOUSE_BUTTON_RIGHT     MED_MOUSE_BUTTON_2
#define MED_MOUSE_BUTTON_MIDDLE    MED_MOUSE_BUTTON_3

#endif //MEDIUM_MOUSEBUTTONS_H
